apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: twitter-app-dev

resources:
  - ../../base

configMapGenerator:
  - name: app-config
    literals:
      - APP_ENV=development
      - APP_DEBUG=true