apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-clone-app
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twitter-clone-app
  template:
    metadata:
      labels:
        app: twitter-clone-app
    spec:
      containers:
      - name: app
        image: your-registry.com/twitter-clone-app:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: host 