apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: twitter-app
type: Opaque
stringData:
  MYSQL_PASSWORD: "secret"
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_USER: "twitter"
  MYSQL_DATABASE: "twitter_clone"