apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: twitter-app
spec:
  selector:
    app: laravel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000
  type: ClusterIP